spring:
  application:
    name: spring-cloud-eureka-client1

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
    register-with-eureka: true
    fetch-registry: true